[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.3.0" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
selene = { github = "Kampfkarren/selene", version = "0.26.1" }
stylua = { github = "johnnymorganz/stylua", version = "0.19.1" }